### PR TITLE
Free CoreGraphics memory allocated in Darwin implementation

### PR DESCRIPTION
**Pull request by pjohnmeyer**
[Asana](https://app.asana.com/0/187295284589485/1113613799026079/f)

_I tried to write a reliable unit test for detecting the memory leak, but couldn't quite figure out how, so for now no automated test for this patch._

Before this patch, CaptureRect was passing the return values of
multiple CoreGraphics methods into each other directly. The
return values of two of these methods, CGImageGetDataProvider and
CGDisplayCreateImage, are required to be released by the caller
per documentation. Because the return values were not even being
captured, they could not be released, resulting in a significant
memory leak.

This patch stores those return values separately and frees them
before returning the captured image.

### CODE REVIEW

**Review by eiwi1101 — APPROVED** [review]
Awesome find! 🎉

**Review by edazdarevic — APPROVED** [review]
Awesome 👍

**Comment by buccolo** [comment]
Nice! Should we send this PR upstream as well?

**Comment by pjohnmeyer** [comment]
@buccolo yes, we will pull this upstream at some point.

**Pull request merged**
